[workspace]

members = [
    "dss-core", # pure rust core 
    "dss-examples" # examples of how to run the code
]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[workspace.dependencies]
anyhow = "1.0.57"
pyo3 = "0.18.1"
pyo3-log = "*"
serde = { version = "1.0.152", features = ["derive"]}
serde_json = "1.0.93"
serde_yaml = "0.9.17"