[package]
name = "generic-ode-solver-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ode_solvers = "0.3.7"
proc-macros = { path = "proc-macros" }
serde = { version = "1.0.152", features = ["derive"]}

